import { Landmark, CreditCard } from "lucide-react";

/**
 * Curated Bank Themes
 * Guaranteed WCAG AA contrast ratio (>= 4.5:1 for all text & badges)
 */
export const BANK_THEMES = {
  "bank-primary": {
    id: "bank-primary",
    nameId: "Emerald Mint (Utama)",
    nameEn: "Emerald Mint (Primary)",
    swatch: "bg-[#00685F]",
    hex: "#00685F",
    bg: "bg-gradient-to-br from-[#00685F] via-[#008A7E] to-[#004D46]",
    shadow: "shadow-2xl shadow-[#00685F]/35 ring-[#00685F]/50",
    border: "border-white/10",
    brand: "GPN",
    icon: Landmark,
  },
  "bank-emerald": {
    id: "bank-emerald",
    nameId: "Emerald Mint",
    nameEn: "Emerald Mint",
    swatch: "bg-[#00685F]",
    hex: "#00685F",
    bg: "bg-gradient-to-br from-[#00685F] via-[#008A7E] to-[#004D46]",
    shadow: "shadow-2xl shadow-[#00685F]/35 ring-[#00685F]/50",
    border: "border-white/10",
    brand: "GPN",
    icon: Landmark,
  },
  "bank-dark": {
    id: "bank-dark",
    nameId: "Obsidian Titanium (Gelap)",
    nameEn: "Obsidian Titanium (Dark)",
    swatch: "bg-[#1E1E1E]",
    hex: "#1E1E1E",
    bg: "bg-gradient-to-br from-[#1E1E1E] via-[#2F2F2F] to-[#121212]",
    shadow: "shadow-xl shadow-black/40 ring-white/20",
    border: "border-white/5",
    brand: "MASTERCARD",
    icon: CreditCard,
  },
  "bank-sapphire": {
    id: "bank-sapphire",
    nameId: "Royal Sapphire (Biru)",
    nameEn: "Royal Sapphire (Blue)",
    swatch: "bg-[#1E3A8A]",
    hex: "#1E3A8A",
    bg: "bg-gradient-to-br from-[#0F2942] via-[#1E3A8A] to-[#0A192F]",
    shadow: "shadow-2xl shadow-blue-900/40 ring-blue-500/50",
    border: "border-white/10",
    brand: "VISA",
    icon: Landmark,
  },
  "bank-ruby": {
    id: "bank-ruby",
    nameId: "Crimson Ruby (Merah)",
    nameEn: "Crimson Ruby (Red)",
    swatch: "bg-[#881337]",
    hex: "#881337",
    bg: "bg-gradient-to-br from-[#4C0519] via-[#881337] to-[#2B030D]",
    shadow: "shadow-2xl shadow-rose-950/40 ring-rose-500/50",
    border: "border-white/10",
    brand: "MASTERCARD",
    icon: CreditCard,
  },
  "bank-purple": {
    id: "bank-purple",
    nameId: "Electric Violet (Ungu)",
    nameEn: "Electric Violet (Purple)",
    swatch: "bg-[#581C87]",
    hex: "#581C87",
    bg: "bg-gradient-to-br from-[#2E1065] via-[#581C87] to-[#1E0B4B]",
    shadow: "shadow-2xl shadow-purple-950/40 ring-purple-500/50",
    border: "border-white/10",
    brand: "VISA",
    icon: Landmark,
  },
  "bank-sunset": {
    id: "bank-sunset",
    nameId: "Bronze Gold (Emas)",
    nameEn: "Bronze Gold (Sunset)",
    swatch: "bg-[#78350F]",
    hex: "#78350F",
    bg: "bg-gradient-to-br from-[#451A03] via-[#78350F] to-[#290E02]",
    shadow: "shadow-2xl shadow-amber-950/40 ring-amber-500/50",
    border: "border-white/10",
    brand: "GPN",
    icon: Landmark,
  },
};

/**
 * Curated E-Wallet Themes
 */
export const EWALLET_THEMES = {
  "wallet": {
    id: "wallet",
    nameId: "Fresh Mint (GoPay)",
    nameEn: "Fresh Mint (GoPay)",
    swatch: "bg-[#00685F]",
    hex: "#00685F",
    isDark: false,
    cardBg: "bg-white border-slate-100",
    iconBox: "bg-brand-50 text-[#00685F]",
    badge: "bg-[#00685F]/15 text-[#00685F]",
    glow: "bg-[#00685F]/5",
    primaryDot: "bg-[#00685F]",
  },
  "wallet-teal": {
    id: "wallet-teal",
    nameId: "Fresh Mint (GoPay)",
    nameEn: "Fresh Mint (GoPay)",
    swatch: "bg-[#00685F]",
    hex: "#00685F",
    isDark: false,
    cardBg: "bg-white border-slate-100",
    iconBox: "bg-brand-50 text-[#00685F]",
    badge: "bg-[#00685F]/15 text-[#00685F]",
    glow: "bg-[#00685F]/5",
    primaryDot: "bg-[#00685F]",
  },
  "wallet-purple": {
    id: "wallet-purple",
    nameId: "Royal Violet (OVO)",
    nameEn: "Royal Violet (OVO)",
    swatch: "bg-[#7C3AED]",
    hex: "#7C3AED",
    isDark: false,
    cardBg: "bg-white border-purple-100/60",
    iconBox: "bg-purple-50 text-purple-700",
    badge: "bg-purple-500/15 text-purple-700",
    glow: "bg-purple-500/5",
    primaryDot: "bg-purple-600",
  },
  "wallet-blue": {
    id: "wallet-blue",
    nameId: "Sky Blue (DANA)",
    nameEn: "Sky Blue (DANA)",
    swatch: "bg-[#0284C7]",
    hex: "#0284C7",
    isDark: false,
    cardBg: "bg-white border-sky-100/60",
    iconBox: "bg-sky-50 text-sky-700",
    badge: "bg-sky-500/15 text-sky-700",
    glow: "bg-sky-500/5",
    primaryDot: "bg-sky-600",
  },
  "wallet-orange": {
    id: "wallet-orange",
    nameId: "Sunset Coral (ShopeePay)",
    nameEn: "Sunset Coral (ShopeePay)",
    swatch: "bg-[#EA580C]",
    hex: "#EA580C",
    isDark: false,
    cardBg: "bg-white border-orange-100/60",
    iconBox: "bg-orange-50 text-orange-700",
    badge: "bg-orange-500/15 text-orange-700",
    glow: "bg-orange-500/5",
    primaryDot: "bg-orange-600",
  },
  "wallet-dark": {
    id: "wallet-dark",
    nameId: "Cyberpunk Dark",
    nameEn: "Cyberpunk Dark",
    swatch: "bg-[#18181B]",
    hex: "#18181B",
    isDark: true,
    cardBg: "bg-gradient-to-br from-[#18181B] via-[#27272A] to-[#09090B] border-white/10 text-white",
    iconBox: "bg-white/10 text-emerald-400",
    badge: "bg-emerald-500/20 text-emerald-300",
    glow: "bg-emerald-500/10",
    primaryDot: "bg-emerald-400",
  },
};

/**
 * Curated Cash Themes
 */
export const CASH_THEMES = {
  "cash": {
    id: "cash",
    nameId: "Clean Ledger (Rupiah)",
    nameEn: "Clean Ledger (Rupiah)",
    swatch: "bg-[#059669]",
    hex: "#059669",
    cardBg: "bg-white border-slate-100",
    iconBox: "bg-slate-50 text-slate-500",
    badge: "bg-slate-100 text-slate-700",
    glow: "bg-slate-50",
  },
  "cash-emerald": {
    id: "cash-emerald",
    nameId: "Clean Ledger (Rupiah)",
    nameEn: "Clean Ledger (Rupiah)",
    swatch: "bg-[#059669]",
    hex: "#059669",
    cardBg: "bg-white border-emerald-100/60",
    iconBox: "bg-emerald-50 text-emerald-700",
    badge: "bg-emerald-100/70 text-emerald-800",
    glow: "bg-emerald-500/5",
  },
  "cash-amber": {
    id: "cash-amber",
    nameId: "Brankas Emas (Gold Vault)",
    nameEn: "Gold Vault",
    swatch: "bg-[#D97706]",
    hex: "#D97706",
    cardBg: "bg-[#FDFCF7] border-amber-200/50",
    iconBox: "bg-amber-50 text-amber-700",
    badge: "bg-amber-100 text-amber-900",
    glow: "bg-amber-500/5",
  },
  "cash-slate": {
    id: "cash-slate",
    nameId: "Titanium Slate",
    nameEn: "Titanium Slate",
    swatch: "bg-[#475569]",
    hex: "#475569",
    cardBg: "bg-white border-slate-200",
    iconBox: "bg-slate-100 text-slate-600",
    badge: "bg-slate-200/70 text-slate-800",
    glow: "bg-slate-500/5",
  },
};

/**
 * Popular Indonesian Presets for Instant One-Click Fill
 */
export const QUICK_PRESETS = [
  { name: "BCA", type: "bank", theme: "bank-primary", title: "Bank BCA", defaultHolder: "PEMILIK REKENING" },
  { name: "Mandiri", type: "bank", theme: "bank-dark", title: "Bank Mandiri", defaultHolder: "" },
  { name: "BRI", type: "bank", theme: "bank-sapphire", title: "Bank BRI", defaultHolder: "" },
  { name: "BNI", type: "bank", theme: "bank-sunset", title: "Bank BNI", defaultHolder: "" },
  { name: "Jago", type: "bank", theme: "bank-purple", title: "Bank Jago", defaultHolder: "" },
  { name: "CIMB", type: "bank", theme: "bank-ruby", title: "Bank CIMB Niaga", defaultHolder: "" },
  { name: "GoPay", type: "ewallet", theme: "wallet-teal", title: "GoPay", defaultHolder: "" },
  { name: "OVO", type: "ewallet", theme: "wallet-purple", title: "OVO", defaultHolder: "" },
  { name: "DANA", type: "ewallet", theme: "wallet-blue", title: "DANA", defaultHolder: "" },
  { name: "ShopeePay", type: "ewallet", theme: "wallet-orange", title: "ShopeePay", defaultHolder: "" },
  { name: "Tunai", type: "cash", theme: "cash-emerald", title: "Dompet Tunai", defaultHolder: "" },
  { name: "Brankas", type: "cash", theme: "cash-amber", title: "Brankas Tunai", defaultHolder: "" },
];
